<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:etd="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" xmlns:kdspr="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2011/06/21/eD/KodyDSPR/" xmlns:zds36l="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/11/20/eD/PITDS36L/" targetNamespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/11/20/eD/PITDS36L/" elementFormDefault="qualified" attributeFormDefault="unqualified" xml:lang="pl">
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/StrukturyDanych_v12-0E.xsd"/>
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2011/06/21/eD/KodyDSPR/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2011/06/21/eD/KodyDSPR/KodyDzialowSpecjalnychProdukcjiRolnej_v2-0E.xsd"/>
	<!--Załącznik do zeznania PIT-36L.-->
	<!-- -->
	<!--Wypełniają podatnicy uzyskujący przychody z działów specjalnych produkcji rolnej, którzy ustalają dochód na podstawie ksiąg rachunkowych lub podatkowej księgi przychodów i rozchodów.-->
	<!-- -->
	<!--Małżonkowie, bez względu na sposób rozliczenia rocznego (indywidualnie czy wspólnie z małżonkiem), składają odrębny załącznik PIT/DS.-->
	<xsd:complexType name="TNaglowek_PIT_DS">
		<xsd:annotation>
			<xsd:documentation>Nagłówek deklaracji</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="KodFormularza">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="zds36l:TKodFormularza_PIT_DS">
							<xsd:attribute name="kodSystemowy" type="xsd:string" use="required" fixed="PIT/DS (6)"/>
							<xsd:attribute name="wersjaSchemy" type="xsd:string" use="required" fixed="2-0E"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="WariantFormularza">
				<xsd:simpleType>
					<xsd:restriction base="xsd:byte">
						<xsd:enumeration value="6"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="TKodFormularza_PIT_DS">
		<xsd:annotation>
			<xsd:documentation>Symbol wzoru formularza</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="PIT/DS"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="Zalacznik_PIT_DS">
		<xsd:annotation>
			<xsd:documentation>INFORMACJA O WYSOKOŚCI DOCHODU (STRATY) Z DZIAŁÓW SPECJALNYCH PRODUKCJI ROLNEJ</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Naglowek" type="zds36l:TNaglowek_PIT_DS">
					<xsd:annotation>
						<xsd:documentation>Nagłówek deklaracji</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="PozycjeSzczegolowe">
					<xsd:annotation>
						<xsd:documentation>Dane dotyczące działów specjalnych produkcji rolnej, łączny przychód, koszty, dochód lub strata podatnika z działów specjalnych produkcji rolnej</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="P_B" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>B. Dane dotyczące działów specjalnych produkcji rolnej</xsd:documentation>
								</xsd:annotation>
								<!--Część B. wypełniają podatnicy prowadzący działy specjalne produkcji rolnej indywidualnie.-->
								<xsd:complexType>
									<xsd:sequence>
										<xsd:annotation>
											<xsd:documentation>B.1. Dane dotyczące działu specjalnego produkcji rolnej</xsd:documentation>
										</xsd:annotation>
										<xsd:sequence>
											<xsd:annotation>
												<xsd:documentation>B.1.1. Określenie działu specjalnego produkcji rolnej</xsd:documentation>
											</xsd:annotation>
											<xsd:element name="P_B7" type="etd:TZnakowy">
												<xsd:annotation>
													<xsd:documentation>Miejsce prowadzenia działu (adres)</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B8" type="etd:TZnakowy">
												<xsd:annotation>
													<xsd:documentation>Rodzaj produkcji</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B9" type="kdspr:TNrDzialu">
												<xsd:annotation>
													<xsd:documentation>Numer działu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B10">
												<xsd:annotation>
													<xsd:documentation>Rozmiar</xsd:documentation>
												</xsd:annotation>
												<xsd:simpleType>
													<xsd:restriction base="etd:TNaturalny">
														<xsd:minExclusive value="0"/>
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
										</xsd:sequence>
										<xsd:sequence>
											<xsd:annotation>
												<xsd:documentation>B.1.2. Dane dotyczące przychodów, kosztów, dochodów / strat</xsd:documentation>
											</xsd:annotation>
											<xsd:element name="P_B11" type="etd:TKwota2Nieujemna" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Przychód</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B12" type="etd:TKwota2Nieujemna" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Koszty uzyskania przychodu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B13" type="etd:TKwota2">
												<xsd:annotation>
													<xsd:documentation>Dochód / strata</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:sequence>
									</xsd:sequence>
									<xsd:attribute name="typ" use="required" fixed="G"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="P_C" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>C. Dane dotyczące działów specjalnych produkcji rolnej</xsd:documentation>
								</xsd:annotation>
								<!--Część C. wypełniają podatnicy prowadzący działy specjalne produkcji rolnej wspólnie z innym podatnikiem/podatnikami lub w formie spółki niebędącej osobą prawną.-->
								<xsd:complexType>
									<xsd:sequence>
										<xsd:annotation>
											<xsd:documentation>C.1. Dane dotyczące działu specjalnego produkcji rolnej</xsd:documentation>
										</xsd:annotation>
										<xsd:sequence>
											<xsd:annotation>
												<xsd:documentation>C.1.1. Określenie działu specjalnego produkcji rolnej</xsd:documentation>
											</xsd:annotation>
											<xsd:element name="P_C14" type="etd:TZnakowy">
												<xsd:annotation>
													<xsd:documentation>Miejsce prowadzenia działu (adres)</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_C15" type="etd:TZnakowy">
												<xsd:annotation>
													<xsd:documentation>Rodzaj produkcji</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_C16" type="kdspr:TNrDzialu">
												<xsd:annotation>
													<xsd:documentation>Numer działu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_C17">
												<xsd:annotation>
													<xsd:documentation>Rozmiar</xsd:documentation>
												</xsd:annotation>
												<xsd:simpleType>
													<xsd:restriction base="etd:TNaturalny">
														<xsd:minExclusive value="0"/>
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
											<xsd:element name="P_C18">
												<xsd:annotation>
													<xsd:documentation>Udział podatnika</xsd:documentation>
												</xsd:annotation>
												<xsd:simpleType>
													<xsd:restriction base="etd:TProcentowy">
														<xsd:minExclusive value="0"/>
													</xsd:restriction>
												</xsd:simpleType>
											</xsd:element>
										</xsd:sequence>
										<xsd:sequence>
											<xsd:annotation>
												<xsd:documentation>C.1.2. Dane dotyczące przychodów, kosztów, dochodów / strat</xsd:documentation>
											</xsd:annotation>
											<xsd:element name="P_C19" type="etd:TKwota2Nieujemna" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Przychód łączny</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_C20" type="etd:TKwota2Nieujemna" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Przychód przypadający na podatnika</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_C21" type="etd:TKwota2Nieujemna" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Koszty uzyskania przychodu łączne</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_C22" type="etd:TKwota2Nieujemna" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Koszty uzyskania przychodu przypadające na podatnika</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_C23" type="etd:TKwota2">
												<xsd:annotation>
													<xsd:documentation>Dochód / strata łączny (-na)</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_C24" type="etd:TKwota2">
												<xsd:annotation>
													<xsd:documentation>Dochód / strata przypadający (-ca) na podatnika</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:sequence>
									</xsd:sequence>
									<xsd:attribute name="typ" use="required" fixed="G"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>D. Łączny przychód, koszty, dochód lub strata podatnika z działów specjalnych produkcji rolnej</xsd:documentation>
								</xsd:annotation>
								<!--Kwoty z poz. od 25 do 28 należy wpisać odpowiednio do wiersza nr 4 w części E.1 lub E.2 zeznania PIT-36 albo do wiersza nr 2 w części E zeznania PIT-36L.-->
								<xsd:element name="P_25" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Przychody</xsd:documentation>
									</xsd:annotation>
									<!--(suma kwot ze wszystkich poz. 11 i 20)-->
								</xsd:element>
								<xsd:element name="P_26" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Koszty uzyskania przychodów</xsd:documentation>
									</xsd:annotation>
									<!--(suma kwot ze wszystkich poz. 12 i 22)-->
								</xsd:element>
								<xsd:choice>
									<xsd:element name="P_27" type="etd:TKwota2Nieujemna">
										<xsd:annotation>
											<xsd:documentation>Dochód</xsd:documentation>
										</xsd:annotation>
										<!--(jeżeli kwota z poz. 25 jest większa od kwoty z poz. 26, od kwoty z poz. 25 należy odjąć kwotę z poz. 26)-->
									</xsd:element>
									<xsd:element name="P_28" type="etd:TKwota2Nieujemna">
										<xsd:annotation>
											<xsd:documentation>Strata</xsd:documentation>
										</xsd:annotation>
										<!--(jeżeli kwota z poz. 26 jest większa od kwoty z poz. 25, od kwoty z poz. 26 należy odjąć kwotę z poz. 25)-->
									</xsd:element>
								</xsd:choice>
							</xsd:sequence>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
