<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:etd="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:zse36="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/PITSE36/" targetNamespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/PITSE36/" elementFormDefault="qualified" attributeFormDefault="unqualified" xml:lang="pl">
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/StrukturyDanych_v12-0E.xsd"/>
	<!--Załącznik do zeznania PIT-36.-->
	<!-- -->
	<!--Formularz jest przeznaczony dla podatników podatku dochodowego od osób fizycznych prowadzących działalność gospodarczą oraz będących wspólnikami spółek niebędących osobą prawną, w rozumieniu ustawy, którzy są beneficjentami pomocy. Formularz stosuje się również do wspólników spółek cywilnych i przedsiębiorstw w spadku.-->
	<xsd:complexType name="TNaglowek_PIT_SE">
		<xsd:annotation>
			<xsd:documentation>Nagłówek deklaracji</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="KodFormularza">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="zse36:TKodFormularza_PIT_SE">
							<xsd:attribute name="kodSystemowy" type="xsd:string" use="required" fixed="PIT/SE (4)"/>
							<xsd:attribute name="wersjaSchemy" type="xsd:string" use="required" fixed="1-0E"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="WariantFormularza">
				<xsd:simpleType>
					<xsd:restriction base="xsd:byte">
						<xsd:enumeration value="4"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="TKodFormularza_PIT_SE">
		<xsd:annotation>
			<xsd:documentation>Symbol wzoru formularza</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="PIT/SE"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="Zalacznik_PIT_SE">
		<xsd:annotation>
			<xsd:documentation>INFORMACJA O WYSOKOŚCI DOCHODU OSIĄGNIĘTEGO Z DZIAŁALNOŚCI GOSPODARCZEJ PROWADZONEJ NA PODSTAWIE ZEZWOLENIA NA TERENIE SPECJALNEJ STREFY EKONOMICZNEJ LUB NA PODSTAWIE DECYZJI O WSPARCIU za rok podatkowy</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Naglowek" type="zse36:TNaglowek_PIT_SE"/>
				<xsd:element name="Podmiot1" type="etd:TIdentyfikatorOsobyFizycznej2"/>
				<xsd:element name="PozycjeSzczegolowe">
					<xsd:annotation>
						<xsd:documentation>Dane dotyczące posiadanych zezwoleń lub decyzji o wsparciu, ustalenie wielkości dochodu podlegającego zwolnieniu z podatku z działalności gospodarczej prowadzonej na podstawie posiadanych zezwoleń na terenie specjalnej strefy ekonomicznej lub na podstawie decyzji o wsparciu, dane dotyczące rozliczenia pomocy publicznej, dane dotyczące cofniętych zezwoleń lub uchylonych decyzji o wsparciu, wielkość kosztów kwalifikowanych, rozliczanych w ramach ulgi B+R</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="P_B" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>Dane dotyczące posiadanych zezwoleń lub decyzji o wsparciu</xsd:documentation>
								</xsd:annotation>
								<!--Należy wskazać wszystkie zezwolenia na prowadzenie działalności na terenie specjalnej strefy ekonomicznej lub decyzje o wsparciu, na podstawie których przedsiębiorca poniósł koszty kwalifikujące się do objęcia pomocą publiczną. W przypadku spółki cywilnej należy podać dane o zezwoleniach lub o decyzjach o wsparciu uzyskanych przez spółkę cywilną lub jej wspólników.-->
								<xsd:complexType>
									<xsd:sequence>
										<xsd:sequence>
											<xsd:annotation>
												<xsd:documentation>Dane identyfikacyjne przedsiębiorcy posiadającego zezwolenie lub decyzję o wsparciu</xsd:documentation>
											</xsd:annotation>
											<xsd:element name="P_B7" type="etd:TZnakowy">
												<xsd:annotation>
													<xsd:documentation>Numer zezwolenia lub decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B8" type="etd:TData">
												<xsd:annotation>
													<xsd:documentation>Data wydania zezwolenia lub decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B9" type="etd:TData">
												<xsd:annotation>
													<xsd:documentation>Data rozpoczęcia działalności</xsd:documentation>
												</xsd:annotation>
												<!--Przez datę rozpoczęcia działalności należy rozumieć rozpoczęcie robót budowlanych związanych z inwestycją lub pierwsze prawnie wiążące zobowiązanie do zamówień urządzeń lub inne zobowiązanie, które sprawia, że inwestycja staje się nieodwracalna, zależnie od tego, co nastąpi najpierw. Zakupu gruntów ani prac przygotowawczych, takich jak uzyskanie zezwoleń i przeprowadzenie studiów wykonalności, nie uznaje się za rozpoczęcie prac - art. 2 pkt 23 rozporządzenia Komisji (UE) nr 651/2014 z dnia 17 czerwca 2014 r. uznającego niektóre rodzaje pomocy za zgodne z rynkiem wewnętrznych w zastosowaniu art. 107 i art. 108 Traktatu. 
Koszty kwalifikowane to koszty, o których mowa w rozporządzeniu Rady Ministrów z dnia 27 grudnia 2022 r. w sprawie pomocy publicznej udzielanej niektórym przedsiębiorcom na realizację nowych inwestycji (Dz. U. poz. 2861), zwanym dalej „rozporządzeniem Rady Ministrów z dnia 27 grudnia 2022 r.”, w zakresie działalności prowadzonej na podstawie decyzji o wsparciu, albo koszty kwalifikowane, o których mowa w rozporządzeniu Rady Ministrów z dnia 10 grudnia 2008 r. w sprawie pomocy publicznej udzielanej przedsiębiorcom działającym na podstawie zezwolenia na prowadzenie działalności gospodarczej na terenach specjalnych stref ekonomicznych (Dz. U. z 2019 r. poz.0 121), zwanym dalej „rozporządzeniem Rady Ministrów z dnia 10 grudnia 2008 r.”, w zakresie działalności prowadzonej na podstawie zezwolenia.-->
											</xsd:element>
											<xsd:element name="P_B10" type="etd:TZnakowy">
												<xsd:annotation>
													<xsd:documentation>Nazwisko i imię lub nazwa spółki</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B11" type="etd:TNrNIP">
												<xsd:annotation>
													<xsd:documentation>Identyfikator podatkowy NIP</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B12" type="etd:TProcentowy">
												<xsd:annotation>
													<xsd:documentation> Udział podatnika w spółce niebędącej osobą prawną (po zaokrągleniu do dwóch miejsc po przecinku)</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:sequence>
										<xsd:sequence>
											<!--Ustalenie dopuszczalnej wartości pomocy publicznej (od dnia uzyskania zezwolenia lub decyzji o wsparciu do ostatniego dnia roku, którego dotyczy zeznanie). Należy wykazać dane dotyczące przedsiębiorcy posiadającego zezwolenie lub decyzję o wsparciu.-->
											<!-- -->
											<!--Zdyskontowaną pomoc publiczną ustala się zgodnie z § 10 ust. 3 rozporządzenia Rady Ministrów z dnia 27 grudnia 2022 r. w przypadku przedsiębiorców prowadzących inwestycję na podstawie decyzji o wsparciu lub § 7 ust. 6 rozporządzenia Rady Ministrów z dnia 10 grudnia 2008 r. w przypadku przedsiębiorców prowadzących inwestycję na podstawie zezwolenia.-->
											<xsd:element name="P_B13" type="etd:TKwota2Nieujemna">
												<xsd:annotation>
													<xsd:documentation>Maksymalna wartość pomocy publicznej - wartość</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B14" type="etd:TKwota2Nieujemna">
												<xsd:annotation>
													<xsd:documentation>Maksymalna wartość pomocy publicznej - zdyskontowana wartość pomocy publicznej lub kosztów kwalifikowanych na dzień uzyskania zezwolenia lub decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:sequence>
										<xsd:sequence>
											<!--Należy wykazać faktycznie poniesione koszty kwalifikujące się do objęcia pomocą publiczną przez przedsiębiorcę wskazanego w poz. 10.-->
											<xsd:element name="P_B15" type="etd:TKwota2Nieujemna">
												<xsd:annotation>
													<xsd:documentation>Koszty kwalifikujące się do objęcia pomocą publiczną narastająco - wartość</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B16" type="etd:TKwota2Nieujemna">
												<xsd:annotation>
													<xsd:documentation>Koszty kwalifikujące się do objęcia pomocą publiczną narastająco - zdyskontowana wartość pomocy publicznej lub kosztów kwalifikowanych na dzień uzyskania zezwolenia lub decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:sequence>
										<xsd:sequence>
											<!--Należy wykazać faktycznie uzyskaną pomoc publiczną przez przedsiębiorcę wskazanego w poz. 10.-->
											<xsd:element name="P_B17" type="etd:TKwota2Nieujemna">
												<xsd:annotation>
													<xsd:documentation>Pomoc udzielona na podstawie ustawy w ramach zezwolenia lub decyzji o wsparciu z poz. 7 - wartość</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B18" type="etd:TKwota2Nieujemna">
												<xsd:annotation>
													<xsd:documentation>Pomoc udzielona na podstawie ustawy w ramach zezwolenia lub decyzji o wsparciu z poz. 7- zdyskontowana wartość pomocy publicznej lub kosztów kwalifikowanych na dzień uzyskania zezwolenia lub decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:sequence>
										<xsd:sequence>
											<!--Należy wykazać wsparcie uzyskane na inwestycję, na którą wydano zezwolenie lub decyzję o wsparciu.-->
											<xsd:element name="P_B19" type="etd:TKwota2Nieujemna">
												<xsd:annotation>
													<xsd:documentation>Inne wsparcie objęte pomocą - wartość</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_B20" type="etd:TKwota2Nieujemna">
												<xsd:annotation>
													<xsd:documentation>Inne wsparcie objęte pomocą - zdyskontowana wartość pomocy publicznej lub kosztów kwalifikowanych na dzień uzyskania zezwolenia lub decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:sequence>
									</xsd:sequence>
									<xsd:attribute name="typ" use="required" fixed="G"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Ustalenie wielkości dochodu podlegającego zwolnieniu z podatku z działalności gospodarczej prowadzonej na podstawie posiadanych zezwoleń na terenie specjalnej strefy ekonomicznej lub na podstawie decyzji o wsparciu. Dane dotyczące zezwolenia (zezwoleń)</xsd:documentation>
								</xsd:annotation>
								<!--W poz. 21 i 22 podatnik wskazuje sumę przychodów i poniesionych kosztów uzyskania przychodów z działalności 
 gospodarczej w roku podatkowym, za który jest składane zeznanie, określonej w zezwoleniach przedsiębiorcy.-->
								<xsd:element name="P_21" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Przychody z działalności gospodarczej określonej w zezwoleniach</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_22" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Koszty uzyskania przychodów z działalności gospodarczej określonej w zezwoleniach</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_23" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Dochód z działalności gospodarczej określonej w zezwoleniach</xsd:documentation>
									</xsd:annotation>
									<!--Od kwoty z poz. 21 należy odjąć kwotę z poz. 22.-->
								</xsd:element>
								<xsd:element name="P_24" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Kwalifikowany dochód z kwalifikowanego prawa własności intelektualnej</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_25" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Strata z działalności gospodarczej określonej w zezwoleniach</xsd:documentation>
									</xsd:annotation>
									<!--Od kwoty z poz. 22 należy odjąć kwotę z poz. 21.-->
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Ustalenie wielkości dochodu podlegającego zwolnieniu z podatku z działalności gospodarczej prowadzonej na podstawie posiadanych zezwoleń na terenie specjalnej strefy ekonomicznej lub na podstawie decyzji o wsparciu. Dane dotyczące decyzji o wsparciu</xsd:documentation>
								</xsd:annotation>
								<!--W poz. 26 i 27 podatnik wskazuje sumę przychodów i kosztów uzyskania przychodów w związku z realizacją nowej inwestycji określonej w decyzjach o wsparciu.-->
								<xsd:element name="P_26" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Przychody z działalności gospodarczej określonej w decyzjach o wsparciu</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_27" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Koszty uzyskania przychodów z działalności gospodarczej określonej w decyzjach o wsparciu</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_28" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Dochód z działalności gospodarczej określonej w decyzjach o wsparciu</xsd:documentation>
									</xsd:annotation>
									<!--Od kwoty z poz. 26 należy odjąć kwotę z poz. 27.-->
								</xsd:element>
								<xsd:element name="P_29" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Kwalifikowany dochód z kwalifikowanego prawa własności intelektualnej</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_30" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Strata z działalności gospodarczej określonej w decyzjach o wsparciu</xsd:documentation>
									</xsd:annotation>
									<!--Od kwoty z poz. 27 należy odjąć kwotę z poz. 26.-->
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Dane dotyczące rozliczenia pomocy publicznej</xsd:documentation>
								</xsd:annotation>
								<!--W poz. 31 i 32 należy wskazać zezwolenia / decyzje o wsparciu, w ramach których podatnik korzysta z pomocy publicznej w formie zwolnienia podatkowego w roku podatkowym, za który jest składane zeznanie.-->
								<xsd:element name="P_D" minOccurs="0" maxOccurs="unbounded">
									<xsd:complexType>
										<xsd:sequence>
											<xsd:sequence>
												<xsd:annotation>
													<xsd:documentation>Dane dotyczące zezwolenia / decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
												<xsd:element name="P_D31" type="etd:TZnakowy">
													<xsd:annotation>
														<xsd:documentation>Numer zezwolenia / decyzji o wsparciu</xsd:documentation>
													</xsd:annotation>
												</xsd:element>
												<xsd:element name="P_D32" type="etd:TData">
													<xsd:annotation>
														<xsd:documentation>Data wydania zezwolenia / decyzji o wsparciu</xsd:documentation>
													</xsd:annotation>
												</xsd:element>
												<xsd:element name="P_D33" type="etd:TKwota2Nieujemna">
													<xsd:annotation>
														<xsd:documentation>Dochód podlegający zwolnieniu z podatku</xsd:documentation>
													</xsd:annotation>
													<!--Kwota wykazana w poz. 33 musi być równa sumie kwot z poz. 23 i 28.-->
												</xsd:element>
											</xsd:sequence>
											<xsd:sequence minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Dane dotyczące beneficjenta pomocy</xsd:documentation>
												</xsd:annotation>
												<!--Wypełniają wyłącznie podatnicy będący wspólnikami spółek osobowych dokonujących odliczenia w ramach zezwolenia / decyzji o wsparciu wskazanych w poz. 31.-->
												<xsd:element name="P_D34" type="etd:TZnakowy">
													<xsd:annotation>
														<xsd:documentation>Nazwa spółki</xsd:documentation>
													</xsd:annotation>
												</xsd:element>
												<xsd:element name="P_D35" type="etd:TNrNIP">
													<xsd:annotation>
														<xsd:documentation>Identyfikator podatkowy NIP</xsd:documentation>
													</xsd:annotation>
												</xsd:element>
											</xsd:sequence>
										</xsd:sequence>
										<xsd:attribute name="typ" use="required" fixed="G"/>
									</xsd:complexType>
								</xsd:element>
								<xsd:element name="P_36" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Razem dochód podlegający zwolnieniu z podatku</xsd:documentation>
									</xsd:annotation>
									<!--Kwota z poz. 36 musi być równa sumie kwot z poz. 23 i 28.-->
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Dane dotyczące cofniętych zezwoleń lub uchylonych decyzji o wsparciu</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_E" minOccurs="0" maxOccurs="unbounded">
									<xsd:complexType>
										<xsd:sequence>
											<xsd:element name="P_E37" type="etd:TZnakowy">
												<xsd:annotation>
													<xsd:documentation>Numer cofniętego zezwolenia lub uchylonej decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_E38" type="etd:TData">
												<xsd:annotation>
													<xsd:documentation>Data cofnięcia zezwolenia lub uchylenia decyzji o wsparciu</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="P_E39" type="etd:TKwota2Nieujemna" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Poatek należny od dochodu wynikającego z cofniętego(-tych) zezwolenia(-ń) albo od dochodu wynikającego z uchylonej(-nych) decyzji o wsparciu, zgodnie z art. 21 ust. 5c pkt 1 i 2 ustawy</xsd:documentation>
												</xsd:annotation>
												<!--Podatnik traci prawo do zwolnienia i jest obowiązany do zapłaty podatku należnego:
- od dochodu wynikającego z cofniętego zezwolenia albo z uchylonej decyzji o wsparciu, jeżeli podatnik korzystał z pomocy publicznej udzielonej w formie zwolnienia wyłącznie w ramach jednego zezwolenia albo w ramach jednej decyzji o wsparciu,
- w wysokości stanowiącej maksymalną dopuszczalną pomoc publiczną określoną w cofniętym zezwoleniu lub w uchylonej decyzji o wsparciu, jeżeli podatnik korzystał ze zwolnienia w ramach więcej niż jednego zezwolenia lub w ramach więcej niż jednej decyzji o wsparciu, albo w ramach zezwolenia lub zezwoleń i decyzji o wsparciu.-->
											</xsd:element>
											<xsd:element name="P_E40" type="etd:TKwota2Nieujemna" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>Podatek zapłacony w związku z cofnięciem zezwolenia lub uchyleniem decyzji o wsparciu, uiszczony w rozliczeniu zaliczki za wybrany okres wpłaty zaliczek</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:sequence>
										<xsd:attribute name="typ" use="required" fixed="G"/>
									</xsd:complexType>
								</xsd:element>
								<xsd:element name="P_41" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Razem podatek podlegający doliczeniu do podatku zgodnie z art. 21 ust. 5c ustawy</xsd:documentation>
									</xsd:annotation>
									<!--Należy wskazać kwotę z poz. 39 pomniejszoną o kwotę z poz. 40.-->
									<!-- -->
									<!--Należy wykazać dane dotyczące zobowiązania podatkowego, które zgodnie art. 70 ustawy z dnia 29 sierpnia 1997 r. - Ordynacja podatkowa (Dz. U. z 2022 r. poz. 2651 z późn. zm.), nie uległy przedawnieniu. W przypadku gdy w roku podatkowym cofnięto więcej niż jedno zezwolenie lub uchylono więcej niż jedną decyzję o wsparciu, podatnik składa kolejny załącznik PIT/SE.-->
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Wielkość kosztów kwalifikowanych, rozliczanych w ramach ulgi B+R</xsd:documentation>
								</xsd:annotation>
								<!--(wypełniają podatnicy, którzy posiadają zezwolenia na prowadzenie działalności na terenie specjalnych stref ekonomicznych lub decyzje o wsparciu)-->
								<xsd:element name="P_42" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Koszty kwalifikowane odliczone od podstawy obliczenia podatku w ramach ulgi B+R</xsd:documentation>
									</xsd:annotation>
									<!-- Przez datę rozpoczęcia działalności należy rozumieć rozpoczęcie robót budowlanych związanych z inwestycją lub pierwsze prawnie wiążące zobowiązanie do zamówień urządzeń lub inne zobowiązanie, które sprawia, że inwestycja staje się nieodwracalna, zależnie od tego, co nastąpi najpierw. Zakupu gruntów ani prac przygotowawczych, takich jak uzyskanie zezwoleń i przeprowadzenie studiów wykonalności, nie uznaje się za rozpoczęcie prac - art. 2 pkt 23 rozporządzenia Komisji (UE) nr 651/2014 z dnia 17 czerwca 2014 r. uznającego niektóre rodzaje pomocy za zgodne z rynkiem wewnętrznych w zastosowaniu art. 107 i art. 108 Traktatu. 
Koszty kwalifikowane to koszty, o których mowa w rozporządzeniu Rady Ministrów z dnia 27 grudnia 2022 r. w sprawie pomocy publicznej udzielanej niektórym przedsiębiorcom na realizację nowych inwestycji (Dz. U. poz. 2861), zwanym dalej „rozporządzeniem Rady Ministrów z dnia 27 grudnia 2022 r.”, w zakresie działalności prowadzonej na podstawie decyzji o wsparciu, albo koszty kwalifikowane, o których mowa w rozporządzeniu Rady Ministrów z dnia 10 grudnia 2008 r. w sprawie pomocy publicznej udzielanej przedsiębiorcom działającym na podstawie zezwolenia na prowadzenie działalności gospodarczej na terenach specjalnych stref ekonomicznych (Dz. U. z 2019 r. poz. 121), zwanym dalej „rozporządzeniem Rady Ministrów z dnia 10 grudnia 2008 r.”, w zakresie działalności prowadzonej na podstawie zezwolenia.-->
								</xsd:element>
								<xsd:element name="P_43" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Numer zezwolenia lub decyzji o wsparciu, w ramach których zostały poniesione koszty kwalifikowane</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>