<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:etd="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" xmlns:ssa="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSEA/" xmlns:ssr="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSER/" xmlns:ssra="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSERA/" targetNamespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSER/" elementFormDefault="qualified" attributeFormDefault="unqualified" xml:lang="pl">
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/StrukturyDanych_v12-0E.xsd"/>
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSEA/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSEA/SSE_A(2)_Z_v9-0E.xsd"/>
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSERA/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSERA/SSE-R_A(3)_Z_v9-0E.xsd"/>
	<xsd:simpleType name="TData">
		<xsd:annotation>
			<xsd:documentation>Ograniczenie dla daty</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="etd:TData">
			<xsd:minInclusive value="2023-01-01"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="TNaglowek_SSE-R">
		<xsd:annotation>
			<xsd:documentation>Nagłówek deklaracji</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="KodFormularza">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="ssr:TKodFormularza_R">
							<xsd:attribute name="kodSystemowy" type="xsd:string" use="required" fixed="SSE-R (5)"/>
							<xsd:attribute name="wersjaSchemy" type="xsd:string" use="required" fixed="10-0E"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="WariantFormularza">
				<xsd:simpleType>
					<xsd:restriction base="xsd:byte">
						<xsd:enumeration value="5"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="OkresOd">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="ssr:TData">
							<xsd:attribute name="poz" type="xsd:string" use="required" fixed="P_4"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="OkresDo">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="ssr:TData">
							<xsd:attribute name="poz" type="xsd:string" use="required" fixed="P_5"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="TKodFormularza_R">
		<xsd:annotation>
			<xsd:documentation>Symbol wzoru formularza</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="SSE-R"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="TIdentyfikatorOsobyFizycznej">
		<xsd:annotation>
			<xsd:documentation>Podstawowy zestaw danych identyfikacyjnych o osobie fizycznej z identyfikatorem NIP</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="NIP" type="etd:TNrNIP">
				<xsd:annotation>
					<xsd:documentation>Identyfikator podatkowy NIP</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ImiePierwsze" type="etd:TImie">
				<xsd:annotation>
					<xsd:documentation>Pierwsze imię</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Nazwisko" type="etd:TNazwisko">
				<xsd:annotation>
					<xsd:documentation>Nazwisko</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="DataUrodzenia" type="etd:TData">
				<xsd:annotation>
					<xsd:documentation>Data urodzenia</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TPodmiotDowolnyBezAdresu">
		<xsd:annotation>
			<xsd:documentation>Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP</xsd:documentation>
		</xsd:annotation>
		<xsd:choice>
			<xsd:element name="OsobaFizyczna" type="ssr:TIdentyfikatorOsobyFizycznej"/>
			<xsd:element name="OsobaNiefizyczna" type="etd:TIdentyfikatorOsobyNiefizycznej"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:simpleType name="TKodStrefy">
		<xsd:annotation>
			<xsd:documentation>Kod strefy</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:byte">
			<xsd:minInclusive value="01"/>
			<xsd:maxInclusive value="14"/>
			<xsd:pattern value="\d{2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="Zalacznik_SSE-R">
		<xsd:annotation>
			<xsd:documentation>ROZLICZENIE PODATKU DOCHODOWEGO OD DOCHODÓW OSIĄGANYCH Z TYTUŁU PROWADZONEJ DZIAŁALNOŚCI NA TERENIE SPECJALNEJ STREFY EKONOMICZNEJ NA PODSTAWIE ZEZWOLENIA ZA ROK PODATKOWY</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Naglowek" type="ssr:TNaglowek_SSE-R"/>
				<xsd:element name="Podmiot1">
					<xsd:complexType>
						<xsd:complexContent>
							<xsd:extension base="ssr:TPodmiotDowolnyBezAdresu">
								<xsd:attribute name="rola" type="xsd:string" use="required" fixed="Składający"/>
							</xsd:extension>
						</xsd:complexContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="PozycjeSzczegolowe">
					<xsd:annotation>
						<xsd:documentation>Ustalenie dopuszczalnej wielkości pomocy publicznej dla przedsiębiorców, o których mowa w art. 5 ust. 2 ustawy, rozliczenie podatku stanowiącego źródło finansowania przedsiębiorców, o których mowa w art. 5 ust. 2 ustawy, obliczenie podatku, który podlegałby zapłacie przy uwzględnieniu zwolnień wynikających z art. 12 ustawy o SSE w brzmieniu obowiązującym w dniu 31 grudnia 2000 r., kwota podatku podlegająca przekazaniu na rachunek funduszu strefowego, wykaz udziałów podatnika w spółkach</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="P_7" type="etd:TWybor1_2">
								<xsd:annotation>
									<xsd:documentation>Składający informację jest podatnikiem podatku dochodowego od osób: 1 - fizycznych, 2 - prawnych</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_8" type="etd:TWybor1_3">
								<xsd:annotation>
									<xsd:documentation>Składana informacja dotyczy przedsiębiorcy będącego w dniu wejścia w życie ustawy: 1 - małym przesiębiorcą, 2 - średnim przesiębiorcą, 3 - dużym przesiębiorcą</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_9" type="ssr:TKodStrefy">
								<xsd:annotation>
									<xsd:documentation>Kod strefy, na której terenie podatnik prowadzi działalność gospodarczą</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_10" type="etd:TZnakowy" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Numer zezwolenia</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_11" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Data wydania zezwolenia</xsd:documentation>
								</xsd:annotation>
								<xsd:simpleType>
									<xsd:restriction base="etd:TData">
										<xsd:minInclusive value="1995-10-01"/>
										<xsd:maxInclusive value="2000-12-31"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="P_12" type="etd:TData" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Data rozpoczęcia działalności</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_13" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Data zmiany zezwolenia</xsd:documentation>
								</xsd:annotation>
								<xsd:simpleType>
									<xsd:restriction base="etd:TData">
										<xsd:minInclusive value="2004-05-01"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="P_14" type="etd:TWybor1_2">
								<xsd:annotation>
									<xsd:documentation>Podatnik prowadzi działalność w sektorze motoryzacyjnym w rozumieniu art. 5 ust. 5 ustawy: 1 - tak, 2 - nie</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_15" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Zwolnienia i preferencje w podatku dochodowym w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy</xsd:documentation>
								</xsd:annotation>
								<!--Zgodnie z przepisami o pomocy publicznej dniem udzielenia pomocy w podatku dochodowym (bez wymogu wydania decyzji) jest dzień, w którym zgodnie z odrębnymi przepisami upływa termin złożenia deklaracji o wysokości osiągniętego dochodu (poniesionej straty). Sporządzając informację np. za rok 2004, w roku 2005 w poz. 15 należy wykazać pomoc wynikającą z zeznania podatkowego za rok 2001 i 2002,  a w poz. 16 za rok 2003.-->
							</xsd:element>
							<xsd:element name="P_16" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Zwolnienia i preferencje w podatku dochodowym w roku podatkowym</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_17" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_18" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w roku podatkowym</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_19" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Ulgi w podatku od nieruchomości, zgodnie z przepisami ustawy o podatkach i opłatach lokalnych w roku, w którym składana jest informacja, do dnia jej złożenia</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation/>
								</xsd:annotation>
								<xsd:element name="P_20A" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Inne</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_20" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Inne w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_21" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Inne w roku podatkowym</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_22" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Inne w roku, w którym składana jest informacja, do dnia jej złożenia</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:element name="P_23" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Łączna wartość pomocy w okresie od 01.01.2001 r. do końca roku poprzedzającego rok podatkowy</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_24" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Łączna wartość pomocy w roku podatkowym</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_25" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Łączna wartość pomocy w roku, w którym składana jest informacja, do dnia jej złożenia</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:sequence>
								<xsd:element name="P_26" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Zakup albo wytworzenie we własnym zakresie środków trwałych lub ich spłata określona w umowie leasingu lub innej umowie o podobnym charakterze, z wyłączeniem środków transportu nabywanych przez przedsiębiorcę prowadzącego działalność gospodarczą w sektorze transportu, pod warunkiem zaliczenia ich - zgodnie z odrębnymi przepisami - do składników majątku podatnika</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_27" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Rozbudowa lub modernizacja istniejących środków trwałych, zaliczonych do wartości początkowej tych środków trwałych zgodnie z przepisami o podatku dochodowym</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_28" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Wytworzenie lub zakup wartości niematerialnych i prawnych związanych z uzyskaniem patentów, licencji operacyjnych bądź opatentowanych licencji typu know-how</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_29" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Wkłady niepieniężne wniesione do przedsiębiorstwa przed dniem 01.05.2004 r., spełniające kryteria kosztów kwalifikujących się do objęcia pomocą - zgodnie z odrębnymi przepisami</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_30" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Łączna wartość kosztów</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:element name="P_31" type="etd:TProcentowy">
								<xsd:annotation>
									<xsd:documentation>Osiągnięta intensywność pomocy</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_32" type="etd:TProcentowy">
								<xsd:annotation>
									<xsd:documentation>Maksymalna intensywność pomocy właściwa dla danego przedsiębiorcy, którego dotyczy informacja, określona w art. 5 ust. 2 i 8 ustawy (w przypadku wspólników spółek osobowych, w tym spółek cywilnych maksymalną intensywność pomocy należy podać proporcjonalnie do udziałów w zyskach spółki)</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_33" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Maksymalna wartość pomocy</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_34" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Wartość pomocy do wykorzystania</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_35" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Dochód osiągnięty z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r. w okresie, za który składana jest niniejsza informacja</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_36" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Równowartość strat poniesionych na tej działalności nieodliczonych w informacjach SSE-R składanych za poprzednie lata podatkowe. Wartość wykazana w poz. 36 nie może przekroczyć wartości wykazanej w poz. 35</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_37" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Dochód osiągnięty w roku objętym informacją, z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r. po odliczeniu straty, ustalony w celu określenia wielkości pomocy</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_38" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Podatek od dochodu wykazanego w poz. 37 wyliczony w celu ustalenia wielkości pomocy publicznej</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_39" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Dopuszczalna kwota udzielenia pomocy po uwzględnieniu rozliczenia podatku za dany rok podatkowy</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_40" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Kwota podatku przekraczająca dopuszczalną intensywność pomocy</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_41" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Podatek od dochodu zwolnionego z tytułu prowadzenia działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_42" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Kwota dochodu zwolnionego z tytułu prowadzenia działalności na terenie strefy na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_43" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dochód osiągnięty w roku podatkowym, w zakresie nieobjętym rozliczeniem pomocy publicznej (zwolnieniem), o którym mowa w części D. W przypadku małego lub średniego przedsiębiorcy należy wpisać kwotę dochodu osiągniętego z działalności w SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r., w okresie, za który składana jest niniejsza informacja</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_44" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Strata poniesiona w roku podatkowym</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:choice minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Wielkość zwolnienia dochodu, jaka przysługiwałaby podatnikowi na podstawie przepisów o specjalnych strefach ekonomicznych w brzmieniu obowiązującym w dniu 31 grudnia 2000 r.</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_45" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Podać procentowo jaka część dochodu byłaby zwolniona, jeżeli zwolnienie zostało określone procentowo</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_46" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Podać kwotowo pełną kwotę zwolnienia</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:choice>
							<xsd:element name="P_47" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dochód, jaki byłby zwolniony od podatku na podstawie przepisów o specjalnych strefach ekonomicznych w brzmieniu obowiązującym w dniu 31 grudnia 2000 r.</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_48" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dochód, jaki nie podlegałby zwolnieniu od podatku</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_49" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Strata nieprzypisana do części źródła dochodu zwolnionej od podatku</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_50" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dochody z działalności innej niż wymieniona w części E.1</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_51" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Straty z działalności innej niż wymieniona w części E.1</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_52" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Dochód</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_53" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Strata przed zmniejszeniami i zwiększeniami</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_54" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Ulgi od dochodu/przychodu</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_55" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Kwota zwiększająca podstawę opodatkowania/zmniejszająca stratę</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_56" type="etd:TKwotaCNieujemna">
								<xsd:annotation>
									<xsd:documentation>Podstawa opodatkowania</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_57" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Strata</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_58" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Podatek obliczony od podstawy opodatkowania z poz. 56</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_59" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Odliczenia od podatku</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_60" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Kwota należnego i zapłaconego podatku dochodowego w terminie złożenia deklaracji o wysokości osiągniętego dochodu, do której informacja stanowi załącznik</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_61" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Kwota podatku, która podlegałaby zapłacie przy uwzględnieniu zwolnień podatkowych wynikających z art. 12 ustawy o SSE w brzmieniu obowiązującym w dniu 31 grudnia 2000 r.</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="P_62" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Kwota podatku podlegająca zgromadzeniu na rachunku Funduszu Strefowego za rok podatkowy</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<!--Sekwencje Dane spółki i adres siedziby należy wypełnić w przypadku, gdy podatnik posiada udział przynajmniej w jednej osobowej spółce handlowej, która prowadzi działalność gospodarczą na terenie SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r. W przypadku posiadania udziałów w większej liczbie osobowych spółek handlowych, prowadzących działalność gospodarczą na terenie SSE na podstawie zezwolenia wydanego przed dniem 01.01.2001 r., niż wskazana w poz. 63 - 72, niewymienione w tej części udziały w spółkach, należy wykazać w załączniku SSE/A. Jednocześnie należy podać liczbę załączników SSE/A w poz. 73. Dane spółki i adres siedziby stosuje się odpowiednio do wspólników spółki cywilnej.-->
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (1)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_63" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_64" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział w %</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_65" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_66" type="ssr:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_67" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (2)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_68" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_69" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział w %</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_70" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_71" type="ssr:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_72" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:element name="P_73" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Informacja o załącznikach SSE/A</xsd:documentation>
								</xsd:annotation>
								<xsd:simpleType>
									<xsd:restriction base="etd:TNaturalny">
										<xsd:maxInclusive value="99"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="P_74" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Informacja o załącznikach SSE-R/A</xsd:documentation>
								</xsd:annotation>
								<xsd:simpleType>
									<xsd:restriction base="etd:TNaturalny">
										<xsd:maxInclusive value="99"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Zalaczniki" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="ssa:Zalacznik_SSE_A" minOccurs="0" maxOccurs="99"/>
							<xsd:element ref="ssra:Zalacznik_SSE-R_A" minOccurs="0" maxOccurs="99"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
