<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:etd="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" xmlns:kk="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/" xmlns:zpm36x="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/11/06/eD/PITPM36X/" targetNamespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/11/06/eD/PITPM36X/" elementFormDefault="qualified" attributeFormDefault="unqualified" xml:lang="pl">
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/StrukturyDanych_v12-0E.xsd"/>
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/KodyKrajow_v13-0E.xsd"/>
	<!--Załącznik do zeznań PIT-36S, PIT-36L i PIT-36LS.-->
	<!-- -->
	<!--Wypełniają podatnicy, którzy na podstawie art. 30dc ust. 2 ustawy zobowiązani są zadeklarować wartość rynkową składników majątku tymczasowo przeniesionych w roku podatkowym, za który jest składane zeznanie, oraz przewidywany termin przeniesienia ich z powrotem na terytorium Rzeczypospolitej Polskiej, jeżeli do dnia złożenia zeznania składniki te pozostają poza terytorium Rzeczypospolitej Polskiej.-->
	<xsd:complexType name="TNaglowek_PIT_PM">
		<xsd:annotation>
			<xsd:documentation>Nagłówek deklaracji</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="KodFormularza">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="zpm36x:TKodFormularza_PIT_PM">
							<xsd:attribute name="kodSystemowy" type="xsd:string" use="required" fixed="PIT/PM (1)"/>
							<xsd:attribute name="wersjaSchemy" type="xsd:string" use="required" fixed="5-0E"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="WariantFormularza">
				<xsd:simpleType>
					<xsd:restriction base="xsd:byte">
						<xsd:enumeration value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="TKodFormularza_PIT_PM">
		<xsd:annotation>
			<xsd:documentation>Symbol wzoru formularza</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="PIT/PM"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TLData">
		<xsd:annotation>
			<xsd:documentation>Ograniczenie dla daty</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="etd:TData">
			<xsd:minInclusive value="2023-01-01"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TKodKrajuWydania">
		<xsd:annotation>
			<xsd:documentation>Kod kraju wydania numeru identyfikacyjnego</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="kk:TKodKraju">
			<xsd:pattern value="P[A-KM-Z]"/>
			<xsd:pattern value="[A-OQ-Z][A-Z]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="Zalacznik_PIT_PM">
		<xsd:annotation>
			<xsd:documentation>INFORMACJA O WYSOKOŚCI WARTOŚCI RYNKOWEJ SKŁADNIKA MAJĄTKU TYMCZASOWO PRZENIESIONEGO POZA TERYTORIUM RZECZYPOSPOLITEJ POLSKIEJ</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Naglowek" type="zpm36x:TNaglowek_PIT_PM">
					<xsd:annotation>
						<xsd:documentation>Nagłówek deklaracji</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="PozycjeSzczegolowe">
					<xsd:annotation>
						<xsd:documentation>Informacja o wysokości wartości rynkowej składnika majątku, o którym mowa w art. 30dc ust. 1 ustawy</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="P_B" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>Informacja o wysokości wartości rynkowej składnika majątku, o którym mowa w art. 30dc ust. 1 ustawy</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:annotation>
											<xsd:documentation>Składnik majątku</xsd:documentation>
										</xsd:annotation>
										<xsd:element name="P_B10" type="zpm36x:TKodKrajuWydania">
											<xsd:annotation>
												<xsd:documentation>Kod kraju, na terytorium którego przeniesiony został składnik majątku, o którym mowa w art. 30dc ust. 1 ustawy</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="P_B11" type="etd:TZnakowy">
											<xsd:annotation>
												<xsd:documentation>Rodzaj składnika majątku, tymczasowo przeniesionego poza terytorium Rzeczypospolitej Polskiej</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="P_B12" type="zpm36x:TLData">
											<xsd:annotation>
												<xsd:documentation>Data przeniesienia składnika majątku poza terytorium Rzeczypospolitej Polskiej</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="P_B13">
											<xsd:annotation>
												<xsd:documentation>Wartość rynkowa składnika majątku tymczasowo przeniesionego poza terytorium Rzeczypospolitej Polskiej</xsd:documentation>
											</xsd:annotation>
											<xsd:simpleType>
												<xsd:restriction base="etd:TKwota2Nieujemna">
													<xsd:minExclusive value="0"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="P_B14" type="zpm36x:TLData" minOccurs="0">
											<xsd:annotation>
												<xsd:documentation>Data przeniesienia składnika majątku z powrotem na terytorium Rzeczypospolitej Polskiej</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="P_B15" type="zpm36x:TLData" minOccurs="0">
											<xsd:annotation>
												<xsd:documentation>Przewidywany termin przeniesienia z powrotem na terytorium Rzeczypospolitej Polskiej składnika majątku, jeżeli do dnia złożenia zeznania składnik ten pozostaje poza terytorium Rzeczypospolitej Polskiej</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="typ" use="required" fixed="G"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
