<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:etd="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" xmlns:ssa="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSEA/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/SSEA/" elementFormDefault="qualified" attributeFormDefault="unqualified" xml:lang="pl">
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/StrukturyDanych_v12-0E.xsd"/>
	<xsd:complexType name="TNaglowek_SSE_A">
		<xsd:annotation>
			<xsd:documentation>Nagłówek deklaracji</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="KodFormularza">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="ssa:TKodFormularza_EA">
							<xsd:attribute name="kodSystemowy" type="xsd:string" use="required" fixed="SSE/A (2)"/>
							<xsd:attribute name="wersjaSchemy" type="xsd:string" use="required" fixed="9-0E"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="WariantFormularza">
				<xsd:simpleType>
					<xsd:restriction base="xsd:byte">
						<xsd:enumeration value="2"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="TKodFormularza_EA">
		<xsd:annotation>
			<xsd:documentation>Symbol wzoru formularza</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="SSE/A"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TKodStrefy">
		<xsd:annotation>
			<xsd:documentation>Kod strefy</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:byte">
			<xsd:minInclusive value="01"/>
			<xsd:maxInclusive value="14"/>
			<xsd:pattern value="\d{2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="Zalacznik_SSE_A">
		<xsd:annotation>
			<xsd:documentation>WYKAZ UDZIAŁÓW W SPÓŁKACH</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Naglowek" type="ssa:TNaglowek_SSE_A"/>
				<xsd:element name="PozycjeSzczegolowe">
					<xsd:annotation>
						<xsd:documentation>Udział w spółkach niemających osobowości prawnej (współwłasność), działających na terenie specjalnej strefy ekonomicznej na podstawie wydanego zezwolenia</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="P_4">
								<xsd:annotation>
									<xsd:documentation>Nr załącznika</xsd:documentation>
								</xsd:annotation>
								<xsd:simpleType>
									<xsd:restriction base="etd:TNaturalny">
										<xsd:minInclusive value="1"/>
										<xsd:maxInclusive value="99"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (1)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_6" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_7" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_8" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_9" type="ssa:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_10" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (2)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_11" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_12" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_13" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_14" type="ssa:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_15" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (3)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_16" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_17" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_18" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_19" type="ssa:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_20" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (4)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_21" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_22" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_23" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_24" type="ssa:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_25" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (5)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_26" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_27" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_28" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_29" type="ssa:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_30" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (6)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_31" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_32" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_33" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_34" type="ssa:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_35" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dane spółki i adres siedziby (7)</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_36" type="etd:TNrNIP">
									<xsd:annotation>
										<xsd:documentation>Identyfikator podatkowy NIP spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_37" type="etd:TProcentowy">
									<xsd:annotation>
										<xsd:documentation>Udział</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_38" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Nazwa pełna</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_39" type="ssa:TKodStrefy">
									<xsd:annotation>
										<xsd:documentation>Kod strefy, na której terenie spółka prowadzi działalność gospodarczą na podstawie zezwolenia wydanego przed dniem 01.01.2001 r.</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_40" type="etd:TZnakowy">
									<xsd:annotation>
										<xsd:documentation>Adres siedziby spółki</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
