<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:zip36="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/PITIP36/" xmlns:etd="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" targetNamespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/10/30/eD/PITIP36/" elementFormDefault="qualified" attributeFormDefault="unqualified" xml:lang="pl">
	<xsd:import namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/" schemaLocation="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/StrukturyDanych_v12-0E.xsd"/>
	<!--Załącznik do zeznania PIT-36. Wypełniają podatnicy, do których ma zastosowanie art. 30ca ustawy.-->
	<!-- -->
	<!--Podatnicy wypełniają załącznik PIT/IP po uprzednim obliczeniu dochodu (straty) dla każdego kwalifikowanego prawa własności intelektualnej.-->
	<!-- -->
	<!--Małżonkowie, bez względu na sposób rozliczenia rocznego (indywidualnie czy wspólnie z małżonkiem), składają odrębny załącznik PIT/IP.-->
	<xsd:complexType name="TNaglowek_PIT_IP">
		<xsd:annotation>
			<xsd:documentation>Nagłówek deklaracji</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="KodFormularza">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="zip36:TKodFormularza_PIT_IP">
							<xsd:attribute name="kodSystemowy" type="xsd:string" use="required" fixed="PIT/IP (5)"/>
							<xsd:attribute name="wersjaSchemy" type="xsd:string" use="required" fixed="1-0E"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="WariantFormularza">
				<xsd:simpleType>
					<xsd:restriction base="xsd:byte">
						<xsd:enumeration value="5"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="TKodFormularza_PIT_IP">
		<xsd:annotation>
			<xsd:documentation>Symbol wzoru formularza</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="PIT/IP"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="Zalacznik_PIT_IP">
		<xsd:annotation>
			<xsd:documentation>INFORMACJA O WYSOKOŚCI DOCHODU (STRATY) Z KWALIFIKOWANYCH PRAW WŁASNOŚCI INTELEKTUALNEJ ORAZ PODATKU DOCHODOWEGO OD OSÓB FIZYCZNYCH za rok podatkowy</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Naglowek" type="zip36:TNaglowek_PIT_IP"/>
				<xsd:element name="Podmiot1" type="etd:TIdentyfikatorOsobyFizycznej2"/>
				<xsd:element name="PozycjeSzczegolowe">
					<xsd:annotation>
						<xsd:documentation>Dane dotyczące kwalifikowanych praw własności intelektualnej, w tym ekspektatyw ich uzyskania, zwanych dalej kwalifikowanymi prawami, dane dotyczące łącznych przychodów, kosztów uzyskania przychodów, dochodów i strat z kwalifikowanych praw, dane dotyczące zwolnienia na podstawie art. 44 ust. 7a ustawy, podstawa obliczenia podatku po uwzględnieniu kwot z części D, zwiększenia / zmniejszenia straty / podstawy obliczenia podatku o wartość wierzytelności i zobowiązań wynikających z transakcji handlowych zawartych w ramach pozarolniczej działalności gospodarczej, obliczenie podatku</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Dane dotyczące kwalifikowanych praw własności intelektualnej, w tym ekspektatyw ich uzyskania, zwanych dalej kwalifikowanymi prawami</xsd:documentation>
								</xsd:annotation>
								<!--Rodzaj kwalifikowanego prawa własności intelektualnej podlegającego ochronie prawnej na podstawie przepisów odrębnych ustaw lub ratyfikowanych umów międzynarodowych, których stroną jest Rzeczpospolita Polska, oraz innych umów międzynarodowych, których stroną jest Unia Europejska, których przedmiot ochrony został wytworzony, rozwinięty lub ulepszony przez podatnika w ramach prowadzonej przez niego działalności badawczo-rozwojowej (art. 30ca ust. 2 ustawy).-->
								<xsd:element name="P_6" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Patent - Liczba</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_7" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Prawo ochronne na wzór użytkowy - Liczba</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_8" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Prawo z rejestracji wzoru przemysłowego - Liczba</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_9" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Prawo z rejestracji topografii układu scalonego - Liczba</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_10" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Dodatkowe prawo ochronne dla patentu na produkt leczniczy lub produkt ochronny roślin - Liczba</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_11" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Prawo z rejestracji produktu leczniczego i produktu leczniczego weterynaryjnego dopuszczonych do obrotu - Liczba</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_12" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Wyłączne prawo, o którym mowa w ustawie z dnia 26 czerwca 2003 r. o ochronie prawnej odmian roślin (Dz. U. z 2021 r. poz. 213) - Liczba</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_13" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Autorskie prawo do programu komputerowego - Liczba</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_14" type="etd:TKwotaCNieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Ekspektatywa - Liczba</xsd:documentation>
									</xsd:annotation>
									<!--Należy wskazać ekspektatywy według stanu na dzień 31 grudnia roku podatkowego, za który jest składane zeznanie.-->
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Dane dotyczące łącznych przychodów, kosztów uzyskania przychodów, dochodów i strat z kwalifikowanych praw</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_15" type="etd:TWybor1" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Kwalifikowany dochód z kwalifikowanego prawa obliczany jest dla tego samego rodzaju produktu lub usługi, lub dla tej samej grupy produktów lub usług: 1 - tak</xsd:documentation>
									</xsd:annotation>
									<!--Wypełnia podatnik, który oblicza dochody zgodnie z art. 30ca ust. 9 ustawy.-->
								</xsd:element>
								<xsd:element name="P_16" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Przychody z kwalifikowanych praw</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_17" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Koszty uzyskania przychodu związane z kwalifikowanymi prawami</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_18" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Dochody z kwalifikowanych praw</xsd:documentation>
									</xsd:annotation>
									<!--W poz. 18 należy wykazać również straty z kwalifikowanych praw poniesione w latach ubiegłych, których wysokość obniża dochód osiągnięty w najbliższych kolejno następujących po sobie pięciu latach podatkowych, z tego samego kwalifikowanego prawa, tego samego rodzaju produktu lub usługi lub tej samej grupy produktów lub usług, w których zostało wykorzystane kwalifikowane prawo.-->
								</xsd:element>
								<xsd:element name="P_19" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Odliczenie zmniejszające dochód z kwalifikowanego prawa z tytułu kosztów uzyskania przychodów poniesionych na działalność badawczo-rozwojową, które doprowadziły do wytworzenia, rozwinięcia lub ulepszenia przez podatnika tego prawa</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_20" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Kwalifikowany dochód (dochody) z kwalifikowanych praw obliczony (obliczone) zgodnie z art. 30ca ust. 4 ustawy</xsd:documentation>
									</xsd:annotation>
									<!--W poz. 20 należy wykazać sumę kwalifikowanych dochodów z kwalifikowanych praw zgodnie z art. 30ca ust. 3 ustawy.-->
								</xsd:element>
								<xsd:element name="P_21" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Dochód z kwalifikowanych praw niepodlegający opodatkowaniu stawką 5%, o której mowa w art. 30ca ust. 1 ustawy</xsd:documentation>
									</xsd:annotation>
									<!--W przypadku gdy wskaźnik, o którym mowa w art. 30ca ust. 4 ustawy, jest niższy niż wartość 1, część dochodu z kwalifikowanych praw nie podlega opodatkowaniu stawką 5%, o której mowa w art. 30ca ust. 1 ustawy.-->
									<!-- -->
									<!--Kwotę z poz. 21 należy przenieść do odpowiedniej pozycji załącznika PIT/B albo do poz. 24, jeżeli dochód korzysta ze zwolnienia (w całości albo w części) na podstawie art. 44 ust. 7a ustawy.-->
								</xsd:element>
								<xsd:element name="P_22" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Strata (straty) z kwalifikowanych praw poniesiona(-e) w bieżącym roku podatkowym</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dochody z kwalifikowanych praw opodatkowane oraz nieopodatkowane stawką 5%, o której mowa w art. 30ca ust. 1 ustawy</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_23" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Kwalifikowany dochód z kwalifikowanych praw podlegający opodatkowaniu stawką 5%, który korzysta ze zwolnienia na podstawie art. 44 ust. 7a ustawy</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_24" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Dochód z kwalifikowanych praw niepodlegający opodatkowaniu stawką 5%, który korzysta ze zwolnienia na podstawie art. 44 ust. 7a ustawy</xsd:documentation>
									</xsd:annotation>
									<!--Kwotę z poz. 24 należy przenieść do odpowiedniej pozycji załącznika PIT/Z.-->
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Dochody z kwalifikowanych praw opodatkowane oraz nieopodatkowane stawką 5%, o której mowa w art. 30ca ust. 1 ustawy</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_25">
									<xsd:annotation>
										<xsd:documentation>Rok podatkowy objęty zwolnieniem, o którym mowa w art. 44 ust. 7a ustawy</xsd:documentation>
									</xsd:annotation>
									<xsd:simpleType>
										<xsd:restriction base="etd:TRok">
											<xsd:minInclusive value="2018"/>
										</xsd:restriction>
									</xsd:simpleType>
									<!--Należy podać rok, w którym podatnik lub zmarły przedsiębiorca korzystał ze zwolnienia na podstawie art. 44 ust. 7a ustawy.-->
								</xsd:element>
								<xsd:element name="P_26" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>20% dochodu wykazanego w załączniku PIT/IP składanym za rok podatkowy objęty zwolnieniem, o którym mowa w art. 44 ust. 7a ustawy</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:choice minOccurs="0">
									<xsd:element name="P_27" type="etd:TKwota2Nieujemna" minOccurs="0">
										<xsd:annotation>
											<xsd:documentation>Strata z kwalifikowanych praw po doliczeniu na podstawie art. 44 ust. 7f i 7l ustawy</xsd:documentation>
										</xsd:annotation>
										<!--Od kwoty z poz. 22 należy odjąć kwotę z poz. 26. W przypadku wartości ujemnej należy wpisać 0.-->
									</xsd:element>
									<xsd:element name="P_28" type="etd:TKwota2Nieujemna" minOccurs="0">
										<xsd:annotation>
											<xsd:documentation>Dochód podlegający doliczeniu do kwalifikowanego dochodu z kwalifikowanych praw na podstawie art. 44 ust. 7f i 7l ustawy</xsd:documentation>
										</xsd:annotation>
										<!--Od kwoty z poz. 26 należy odjąć kwotę z poz. 22. W przypadku wartości ujemnej należy wpisać 0.-->
									</xsd:element>
								</xsd:choice>
							</xsd:sequence>
							<xsd:element name="P_29" type="etd:TKwotaCNieujemna">
								<xsd:annotation>
									<xsd:documentation>Podstawa obliczenia podatku (po zaokrągleniu do pełnych złotych)</xsd:documentation>
								</xsd:annotation>
								<!--Do kwoty z poz. 20, pomniejszonej o kwotę z poz. 23, należy dodać kwotę z poz. 28.-->
							</xsd:element>
							<!--F. ZWIĘKSZENIA / ZMNIEJSZENIA STRATY / PODSTAWY OBLICZENIA PODATKU O WARTOŚĆ WIERZYTELNOŚCI I ZOBOWIĄZAŃ WYNIKAJĄCYCH Z TRANSAKCJI HANDLOWYCH ZAWARTYCH W RAMACH POZAROLNICZEJ DZIAŁALNOŚCI GOSPODARCZEJ-->
							<xsd:sequence minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Zwiększenia / zmniejszenia straty o wartość wierzytelności i zobowiązań wynikających z transakcji handlowych zawartych w ramach pozarolniczej działalności gospodarczej</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_30" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Zwiększenia straty na podstawie art. 26i ust. 2 pkt 1 oraz ust. 8 ustawy</xsd:documentation>
									</xsd:annotation>
									<!--Należy wpisać kwotę zwiększającą stratę w części, w jakiej nie podlega uwzględnieniu w zeznaniu PIT-36, PIT-36S, PIT-36L albo PIT-36LS - jeżeli kwota w poz. 27 jest większa od 0.-->
									<!-- -->
									<!--Należy wpisać:
- wartość wierzytelności, które do dnia złożenia zeznania podatkowego nie zostały uregulowane lub zbyte; uwzględnia się wartość wierzytelności w części, w jakiej nie została uregulowana lub zbyta, oraz
- wartość zobowiązań uregulowanych w roku podatkowym, które w poprzednich latach zwiększyły podstawę obliczenia podatku lub zmniejszyły stratę; uwzględnia się wartość zobowiązania w części, w jakiej zostało uregulowane w roku podatkowym.
Podatnik będący wspólnikiem spółki niebędącej osobą prawną wpisuje wartość wierzytelności/zobowiązań stosownie do swojego udziału.-->
								</xsd:element>
								<xsd:element name="P_31" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Strata po zwiększeniu</xsd:documentation>
									</xsd:annotation>
									<!--Do kwoty z poz. 27 należy dodać kwotę z poz. 30.-->
								</xsd:element>
								<xsd:element name="P_32" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Zmniejszenia straty na podstawie art. 26i ust. 2 pkt 2 oraz ust. 7 ustawy</xsd:documentation>
									</xsd:annotation>
									<!--Należy wpisać kwotę zmniejszającą stratę w części, w jakiej nie podlega uwzględnieniu w zeznaniu PIT-36, PIT-36S, PIT-36L albo PIT-36LS - jeżeli kwota w poz. 27 jest większa od 0.-->
									<!-- -->
									<!--Należy wpisać:
- wartość zobowiązań, które do dnia złożenia zeznania podatkowego nie zostały uregulowane; uwzględnia się wartość zobowiązania w części, w jakiej nie zostało uregulowane, oraz
- wartość wierzytelności uregulowanych lub zbytych w roku podatkowym, które w poprzednich latach zmniejszyły podstawę obliczenia podatku lub zwiększyły stratę; uwzględnia się wartość wierzytelności w części, w jakiej została uregulowana lub zbyta.
Podatnik będący wspólnikiem spółki niebędącej osobą prawną wpisuje wartość wierzytelności/zobowiązań stosownie do swojego udziału.--> 
								</xsd:element>
								<xsd:element name="P_33" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Strata po zmniejszeniu - do odliczenia w kolejnych latach</xsd:documentation>
									</xsd:annotation>
									<!--Od kwoty z poz. 31 należy odjąć kwotę z poz. 32. Jeżeli różnica jest liczbą ujemną, należy wpisać 0.-->
								</xsd:element>
								<xsd:element name="P_34" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Kwota podlegająca doliczeniu do podstawy obliczenia podatku</xsd:documentation>
									</xsd:annotation>
									<!--Od kwoty z poz. 32 należy odjąć kwotę z poz. 31. Jeżeli różnica jest liczbą ujemną, należy wpisać 0.-->
								</xsd:element>
							</xsd:sequence>
							<xsd:element name="P_35" type="etd:TKwota2Nieujemna">
								<xsd:annotation>
									<xsd:documentation>Podstawa obliczenia podatku</xsd:documentation>
								</xsd:annotation>
								<!--Do kwoty z poz. 29 należy dodać kwotę z poz. 34.-->
							</xsd:element>
							<!--Zwiększenia i zmniejszenia podstawy obliczenia podatku o wartość wierzytelności i zobowiązań wynikających z transakcji handlowych zawartych w ramach pozarolniczej działalności gospodarczej -->
							<xsd:element name="P_36" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Wartość zobowiązań i wierzytelności zwiększających podstawę obliczenia podatku, o których mowa w art. 26i ust. 1 pkt 2 i ust. 7 ustawy</xsd:documentation>
								</xsd:annotation>
								<!--Należy wpisać kwotę zwiększającą podstawę obliczenia podatku w części, w jakiej nie podlega uwzględnieniu w zeznaniu PIT-36, PIT-36S, PIT-36L albo PIT-36LS, jeżeli kwota w poz. 27 jest równa 0.-->
<!-- -->
<!--Należy wpisać:
- wartość zobowiązań, które do dnia złożenia zeznania podatkowego nie zostały uregulowane; uwzględnia się wartość zobowiązania w części, w jakiej nie zostało uregulowane, oraz
- wartość wierzytelności uregulowanych lub zbytych w roku podatkowym, które w poprzednich latach zmniejszyły podstawę obliczenia podatku lub zwiększyły stratę; uwzględnia się wartość wierzytelności w części, w jakiej została uregulowana lub zbyta.
Podatnik będący wspólnikiem spółki niebędącej osobą prawną wpisuje wartość wierzytelności/zobowiązań stosownie do swojego udziału.-->
							</xsd:element>
							<xsd:element name="P_37" type="etd:TKwota2Nieujemna" minOccurs="0">
								<xsd:annotation>
									<xsd:documentation>Wartość wierzytelności i zobowiązań zmniejszających podstawę obliczenia podatku, o których mowa w art. 26i ust. 1 pkt 1 i ust. 8 ustawy</xsd:documentation>
								</xsd:annotation>
								<!--Należy wpisać kwotę zmniejszającą podstawę obliczenia podatku w części, w jakiej nie podlega uwzględnieniu w zeznaniu PIT-36, PIT-36S, PIT-36L albo PIT-36LS, jeżeli kwota w poz. 27 jest równa 0.-->
								<!-- -->
								<!--Należy wpisać:
- wartość wierzytelności, które do dnia złożenia zeznania podatkowego nie zostały uregulowane lub zbyte; uwzględnia się wartość wierzytelności w części, w jakiej nie została uregulowana lub zbyta, oraz
- wartość zobowiązań uregulowanych w roku podatkowym, które w poprzednich latach zwiększyły podstawę obliczenia podatku lub zmniejszyły stratę; uwzględnia się wartość zobowiązania w części, w jakiej zostało uregulowane w roku podatkowym.
Podatnik będący wspólnikiem spółki niebędącej osobą prawną wpisuje wartość wierzytelności/zobowiązań stosownie do swojego udziału.-->
							</xsd:element>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Podstawa obliczenia podatku po uwzględnieniu kwot z części F.3.1. i F.3.2.</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_38" type="etd:TKwota2Nieujemna">
									<xsd:annotation>
										<xsd:documentation>Podstawa obliczenia podatku po zwiększeniach i zmniejszeniach</xsd:documentation>
									</xsd:annotation>
									<!--Do kwoty z poz. 35 należy dodać kwotę z poz. 36, a następnie odjąć kwotę z poz. 37. Jeżeli wynik jest liczbą ujemną, należy wpisać 0.-->
								</xsd:element>
								<xsd:element name="P_39" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Wartość nieodliczonych w poprzednich latach wierzytelności i zobowiązań zmniejszających podstawę obliczenia podatku</xsd:documentation>
									</xsd:annotation>
									<!--Kwota odliczenia nie może być wyższa od kwoty z poz. 38.-->
								</xsd:element>
								<xsd:element name="P_40" type="etd:TKwotaCNieujemna">
									<xsd:annotation>
										<xsd:documentation>Podstawa obliczenia podatku po odliczeniu (po zaokrągleniu do pełnych złotych)</xsd:documentation>
									</xsd:annotation>
									<!--Od kwoty z poz. 38 należy odjąć kwotę z poz. 39.-->
								</xsd:element>
							</xsd:sequence>
							<xsd:sequence>
								<xsd:annotation>
									<xsd:documentation>Obliczenie podatku</xsd:documentation>
								</xsd:annotation>
								<xsd:element name="P_41" type="etd:TKwotaCNieujemna">
									<xsd:annotation>
										<xsd:documentation>Obliczony podatek zgodnie z art. 30ca ust. 1 ustawy przy zastosowaniu stawki 5%</xsd:documentation>
									</xsd:annotation>
									<!--Należy obliczyć podatek od kwoty z poz. 40.-->
								</xsd:element>
								<xsd:element name="P_42" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Doliczenia do podatku</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="P_43" type="etd:TKwota2Nieujemna" minOccurs="0">
									<xsd:annotation>
										<xsd:documentation>Odliczenia od podatku</xsd:documentation>
									</xsd:annotation>
									<!--Kwota odliczeń nie może przekroczyć sumy kwot z poz. 41 i 42.-->
								</xsd:element>
								<xsd:element name="P_44" type="etd:TKwotaCNieujemna">
									<xsd:annotation>
										<xsd:documentation>Podatek obliczony zgodnie z art. 30ca ust. 1 ustawy po uwzględnieniu doliczeń i odliczeń z poz. 42 i 43 (po zaokrągleniu do pełnych złotych)</xsd:documentation>
									</xsd:annotation>
									<!--Do kwoty z poz. 41 należy dodać kwotę z poz. 42, a następnie odjąć kwotę z poz. 43. Kwotę z poz. 44 należy przenieść do odpowiednich pozycji zeznania PIT-36 albo do odpowiedniej pozycji zeznania PIT-36S, albo do odpowiedniej pozycji zeznania PIT-36L, albo do odpowiedniej pozycji zeznania PIT-36LS.-->
								</xsd:element>
							</xsd:sequence>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
